### ISSUE TITLE
Failed to connect to all addresses

### ISSUE THREAD

**Issue by ontheway16** [isarsoft/yolov4-triton-tensorrt#15]
Hello, under kubernetes, I am receiving following error from client.py which is trying to connect to a worker node via -u IP: portnumber :

$ python client.py -u 192.168.1.26:30353 imageTraceback (most recent call last):  File "client.py", line 120, in <module>    if not triton_client.is_server_live():  File "/home/user/miniconda3/envs/yolov4-triton/lib/python3.7/site-packages/tritonclient/grpc/init.py", line 217, in is_server_live    raise_error_grpc(rpc_error)  File "/home/user/miniconda3/envs/yolov4-triton/lib/python3.7/site-packages/tritonclient/grpc/init.py", line 61, in raise_error_grpc    raise get_error_grpc(rpc_error) from Nonetritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses

**Comment by ontheway16** [comment]
nevermind, solved. requesting from http port instead of grpc.

**Comment by chiyukunpeng** [comment]
hi, I also receiving this error by requesting from http port instead of grpc.

**error**
(py38torch16) cp@ubuntu:~/project/yolov5/client$ python client.py dummy
Traceback (most recent call last):
  File "client.py", line 120, in <module>
    if not triton_client.is_server_live():
  File "/home/cp/anaconda3/envs/py38torch16/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 217, in is_server_live
    raise_error_grpc(rpc_error)
  File "/home/cp/anaconda3/envs/py38torch16/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses

**server**
I1204 05:35:19.935501 1 grpc_server.cc:1939] Started GRPCService at 0.0.0.0:8001
I1204 05:35:19.935519 1 http_server.cc:1411] Starting HTTPService at 0.0.0.0:8000
I1204 05:35:19.978388 1 http_server.cc:1426] Starting Metrics Service at 0.0.0.0:8002
I1204 05:35:19.983894 1 server.cc:224] Polling model repository

**Comment by chiyukunpeng** [comment]
> hi, I also receive this error by requesting from http port instead of grpc.
> 
> **error**
> (py38torch16) cp@ubuntu:~/project/yolov5/client$ python client.py dummy
> Traceback (most recent call last):
> File "client.py", line 120, in 
> if not triton_client.is_server_live():
> File "/home/cp/anaconda3/envs/py38torch16/lib/python3.8/site-packages/tritonclient/grpc/**init**.py", line 217, in is_server_live
> raise_error_grpc(rpc_error)
> File "/home/cp/anaconda3/envs/py38torch16/lib/python3.8/site-packages/tritonclient/grpc/**init**.py", line 61, in raise_error_grpc
> raise get_error_grpc(rpc_error) from None
> tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses
> 
> **server**
> I1204 05:35:19.935501 1 grpc_server.cc:1939] Started GRPCService at 0.0.0.0:8001
> I1204 05:35:19.935519 1 http_server.cc:1411] Starting HTTPService at 0.0.0.0:8000
> I1204 05:35:19.978388 1 http_server.cc:1426] Starting Metrics Service at 0.0.0.0:8002
> I1204 05:35:19.983894 1 server.cc:224] Polling model repository

I think the reason of that is HTTPService is starting instead of started. 
My triton is 20.03.
how to solve it? thanks.
