### ISSUE TITLE
Support for Scaled-YOLOv4

### ISSUE THREAD

**Issue by LukeAI** [isarsoft/yolov4-triton-tensorrt#22]
Does this repo. support [Scaled-YOLOv4](https://github.com/WongKinYiu/ScaledYOLOv4)? In particular [yolov4-csp](https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-csp) ?

**Comment by philipp-schmidt** [comment]
No not yet, but it will be added in the coming weeks. The changes are minor.

**Comment by philipp-schmidt** [comment]
Hi @LukeAI 

In the meantime you can check out a different implementation by @jkjung-avt 
https://github.com/jkjung-avt/tensorrt_demos#demo-5-yolov4

When you have created the engine with his repo you can deploy it identically as described in my README.
You might have to change the client postprocessing code a little, but he has well commented code for that as well.

**Comment by philipp-schmidt** [comment]
Hi @LukeAI, I have updated the repo. It does now fully support Scaled-YOLOv4. The plugin is compatible, so you can e.g. try yolov4-tiny by running `./main -n yolov4tiny`.

I currently still have trouble to convert old darknet weights (non-"scaled") because the `route group_id` parameter is not supported and is called `route_lhalf`. So I need to fix this. But all models which can be run in the ScaledYolov4 Pytorch Implementation can be converted.

**Comment by philipp-schmidt** [comment]
Examples are under `networks`

**Comment by philipp-schmidt** [comment]
Network definition is basically the same as here: https://github.com/tjuskyzhang/Scaled-YOLOv4-TensorRT/tree/master/yolov4-csp-tensorrt
